name: Deploy Portfolio

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Étape 1 : Checkout du code
      - name: Checkout code
        uses: actions/checkout@v2

      # Étape 2 : Installer Node.js et les dépendances
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install

      # Étape 3 : Construire le projet
      - name: Build the project
        run: npm run build

      # Étape 4 : Déployer les fichiers sur le VPS
      - name: Deploy to server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}            # L'adresse IP ou le domaine de ton VPS
          username: ${{ secrets.SSH_USERNAME }}    # Le nom d'utilisateur pour la connexion SSH
          key: ${{ secrets.SSH_KEY }}              # La clé privée stockée dans les secrets GitHub
          source: build/*                          # Le dossier contenant les fichiers à transférer
          target: /var/www/portfolio/              # Le chemin cible sur ton VPS
          port: 22                                 # Le port SSH (généralement 22)
          timeout: 30s
          command_timeout: 10m
          use_insecure_cipher: false
          rm: false
          debug: true
