name: Deploy Portfolio

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code source
      - name: Checkout code
        uses: actions/checkout@v2

      # Étape 2 : Installer les dépendances et builder le projet
      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      # Étape 3 : Archiver le build pour le transfert
      - name: Archive production build
        run: |
          tar -czf portfolio.tar.gz build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Étape 1 : Se connecter au serveur via SSH (avec une clé privée SSH ajoutée dans les secrets)
      - name: Deploy to VPS
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: portfolio.tar.gz
          target: /var/www/portfolio/

      # Étape 2 : Se connecter via SSH pour extraire les fichiers
      - name: Extract files on VPS
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/portfolio
            tar -xzf portfolio.tar.gz
            rm portfolio.tar.gz
            # Redémarrer Apache si nécessaire
            sudo systemctl restart apache2
