name: Deploy Portfolio

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code source
      - name: Checkout code
        uses: actions/checkout@v2

      # Étape 2 : Configurer Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: npm install

      # Étape 4 : Construire l'application React
      - name: Build the React application
        run: npm run build

      # Étape 5 : Créer un fichier tar à partir du répertoire de build
      - name: Create tarball
        run: tar -czvf portfolio.tar.gz -C build .

      # Étape 6 : Se connecter à Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Étape 7 : Construire et pousser l'image Docker vers Docker Hub
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/portfolio:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/portfolio:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Étape 1 : Déployer sur le VPS
      - name: Deploy to VPS
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: portfolio.tar.gz
          target: /var/www/portfolio/
          port: 22
